### ISSUE TITLE
set2/13/input.txt, line #26 should not be blank

### ISSUE THREAD

**Issue by theanor** [rcemper/AoC2022-results#1]
Dear Robert,

The input file for day 13 in set 2 has an extra empty line at line # 26.

This was breaking my implementation (for part one only). Without this blank line, I get the result in result.txt for part one. Part 2 is not affected as it is based on sorting all individual packets (vs grouping in pairs).

I uploaded the fixed file in [github repo](https://github.com/theanor/idc-aoc-2022-theanor/blob/master/data/set2/13/input.txt) for this AoC 2022.

Thank you for your support, the contest is really enjoyable (even if I'm a bit old and rusty for this kind sport ;)

kind regards,

Robert ;-)

**Comment by rcemper** [comment]
Thanks for pointing me to this mistake!
I fixed it. It was not in my  original input.
I didn't. recognize as my test wasn't sensitive to the extra empty line.

Great job !
