### ISSUE TITLE
There may be an issue with results for set 1 day 18

### ISSUE THREAD

**Issue by theanor** [rcemper/AoC2022-results#2]
Hi Robert,

Results from my implementation are correct for my input and are also the same as result.txt for set 2 day 18, but for set 1, results.txt has  :

- part 1 = 4192
- part 2 = 2520

whereas my implementation returns :

- part 1 = 4310
- part 2 = 2466

Using another solution (downloaded from AoC reddit thread)  I get the same results as mine for this input.

Of course I'm not 100% sure my code and the one I used to cross-check are not affected by the same flaw... but there _may_ be an issue with set 1 day 18 result.txt.

Thank you and season's greetings,

R.

**Comment by rcemper** [comment]
You are right. 
It was a mistake during upöaos and is fixed now

Thanks for notification
